KeypointDetector Class Reference
Keypoint detector class.
#include <keypoint.h>
Public Member Functions
KeypointDetector (char *basisfile)
Constructs a new KeypointDetector object.
void RecalcKeys (Image *image, vector< Keypoint * > &keys)
Recalculates local descriptor of keys on the given image.
Static Public Member Functions
static void writeKeysToFile (vector< Keypoint * > &keys, char *fn)
Writes keypoints to a file.
static vector< Keypoint * > readKeysFromFile (char *fn)
Read keys from a file.
static vector< Keypoint * > readPatchesFromFile (char *fn)
Read patches from a file.
static void getPatches (Image *im, vector< Keypoint * > &keys, int patchsize)
Get image patch.
static void writePatchesToFile (vector< Keypoint * > &keys, char *fn, int patchsize)
Write patches to file.
Private Member Functions
void MakeKeypointPCA (Keypoint *key, Image *blur)
Computes the PCA local descriptor of a keypoint Stores local descriptor in keypoint ld.
void MakeKeypointPatch (Keypoint *key, Image *blur, float v[GPLEN])
Extracts the image gradient patch of a keypoint.
void ComputeLocalDescr (vector< Keypoint * > &kps, vector< vector< Image * > > &LOctaves)
Computes the PCA local descriptor for keypoints.
Static Private Member Functions
static Image * ScaleInitImage (Image *image)
Scales and blurs input image to make base image.
static vector< vector< Image * > > BuildGaussianOctaves (Image *image)
Given a base image, computes a gaussian pyramid.
static vector< Image * > BuildGaussianScales (Image *image)
Given a base image, computes a gaussian pyramid for a particular octave.
static void RecalcKeyIndices (vector< Keypoint * > &keys)
static void MakeLocalPatch (Keypoint *key, Image *blur, int windowsize)
static void ComputeLocalPatches (vector< Keypoint * > &kps, vector< vector< Image * > > &LOctaves, int patchsize)
Private Attributes
float avgs [GPLEN]
average local descriptor value. Used in PCA.
float eigs [EPCALEN][GPLEN]
PCA basis vectors.
Detailed Description
Keypoint detector class.
Finds keypoints using David Lowe's SIFT algorithm. Computes local descriptors using PCASIFT.
Limiations: Does not fully implement Lowe's SIFT algorithm. Does not interpolate in location and scale.
Constructor & Destructor Documentation
KeypointDetector::KeypointDetector (char * basisfile)
Constructs a new KeypointDetector object.
Parameters
basisfile File name of the PCA basis vector file and averages.
References avgs, eigs, EPCALEN, GPLEN, and PCALEN.
Member Function Documentation
vector< vector< Image * > > KeypointDetector::BuildGaussianOctaves (Image * image) [static], [private]
Given a base image, computes a gaussian pyramid.
Base image must be blurred and scaled appropriately.
Parameters
image Base image for the bottom of the Gaussian pyramid.
Returns
Vector of vector of Image *. Outside vector are the octaves. Inside vector are the scales of images.
See also
BuildGaussianScales()
BuildDOGOctaves()
ScaleInitImage()
References BuildGaussianScales(), Image::clone(), Image::halfSizeImage(), Image::height, MAXOCTAVES, SCALESPEROCTAVE, and Image::width.
Referenced by getPatches(), and RecalcKeys().
vector< Image * > KeypointDetector::BuildGaussianScales (Image * image) [static], [private]
Given a base image, computes a gaussian pyramid for a particular octave.
Number of scales in an octave based on SCALESPEROCTAVE.
Parameters
image Base image for the bottom of this octave.
Returns
Vector of Image *, the scales of this octave.
See also
BuildGaussianOctaves()
References BlurImage(), Image::clone(), Image::height, SCALESPEROCTAVE, SIGMA, and Image::width.
Referenced by BuildGaussianOctaves().
void KeypointDetector::ComputeLocalDescr (vector< Keypoint * > & kps, vector< vector< Image * > > & LOctaves) [private]
Computes the PCA local descriptor for keypoints.
Stores local desciptor in the ld field of the Keypoint.
Parameters
kps Keypoints localized in space, scale, and orientation.
LOctaves Gaussian pyramid.
See also
BuildGaussianOctaves()
References MakeKeypointPCA().
Referenced by RecalcKeys().
void KeypointDetector::ComputeLocalPatches (vector< Keypoint * > & kps, vector< vector< Image * > > & LOctaves, int patchsize) [static], [private]
References MakeLocalPatch().
Referenced by getPatches().
void KeypointDetector::getPatches (Image * im, vector< Keypoint * > & keys, int patchsize) [static]
Get image patch.
Parameters
image Image to calculate.
keys Vector of keys with position already calculated.
patchsize size of square patch in pixels.
References BuildGaussianOctaves(), ComputeLocalPatches(), RecalcKeyIndices(), and ScaleInitImage().
Referenced by main().
void KeypointDetector::MakeKeypointPatch (Keypoint * key, Image * blur, float v[GPLEN]) [private]
Extracts the image gradient patch of a keypoint.
Size of image patch determined by PatchSize. Gradient patch is 2 pixels smaller in each dimension. We compute the gradient in both the x and y direction.
Parameters
key Keypoint localized in space, scale, and orientation.
blur Gaussian image closest in scale to the keypoint.
v Return. Gradient patch flattened into one long vector. We store gx and gy interleaved.
References Keypoint::fscale, Image::getPixelBI(), Keypoint::ori, PatchMag, PatchSize, SCALESPEROCTAVE, Image::setPixel(), SIGMA, Keypoint::sx, and Keypoint::sy.
Referenced by MakeKeypointPCA().
void KeypointDetector::MakeKeypointPCA (Keypoint * key, Image * blur) [private]
Computes the PCA local descriptor of a keypoint Stores local descriptor in keypoint ld.
Parameters
key A keypoint localized in space, scale, and orientation.
blur The Gaussian scale closest to the scale of the keypoint.
References avgs, eigs, EPCALEN, GPLEN, Keypoint::ld, MakeKeypointPatch(), and Normvec().
Referenced by ComputeLocalDescr().
void KeypointDetector::MakeLocalPatch (Keypoint * key, Image * blur, int windowsize) [static], [private]
References Keypoint::fscale, Image::getPixelBI(), Keypoint::ori, Keypoint::patch, PatchMag, PatchSize, SCALESPEROCTAVE, Image::setPixel(), SIGMA, Keypoint::sx, and Keypoint::sy.
Referenced by ComputeLocalPatches().
vector< Keypoint * > KeypointDetector::readKeysFromFile (char * fn) [static]
Read keys from a file.
Parameters
fn File name of input.
Returns
Vector of keys.
References Keypoint::gscale, Keypoint::ld, Keypoint::ori, Keypoint::x, and Keypoint::y.
Referenced by main().
vector< Keypoint * > KeypointDetector::readPatchesFromFile (char * fn) [static]
Read patches from a file.
Parameters
fn File name of input.
Returns
Vector of keys.
References Keypoint::gscale, Keypoint::ori, Keypoint::patch, Image::setPixel(), Keypoint::x, and Keypoint::y.
Referenced by main().
void KeypointDetector::RecalcKeyIndices (vector< Keypoint * > & keys) [static], [private]
References DOUBLE_BASE_IMAGE_SIZE, Keypoint::fscale, Keypoint::gscale, Keypoint::octave, Keypoint::scale, SCALESPEROCTAVE, SIGMA, Keypoint::sx, Keypoint::sy, Keypoint::x, and Keypoint::y.
Referenced by getPatches(), and RecalcKeys().
void KeypointDetector::RecalcKeys (Image * image, vector< Keypoint * > & keys)
Recalculates local descriptor of keys on the given image.
Given localized keys, calculate local descriptor.
Parameters
image Image to calculate.
keys Vector of keys with position already calculated.
References BuildGaussianOctaves(), ComputeLocalDescr(), RecalcKeyIndices(), and ScaleInitImage().
Referenced by main().
Image * KeypointDetector::ScaleInitImage (Image * image) [static], [private]
Scales and blurs input image to make base image.
Possibly doubles image size, based on DOUBLE_BASE_IMAGE_SIZE. Blur image based on difference of SIGMA and INITSIGMA.
Parameters
image Raw image to find keypoints on.
Returns
Base image for the bottom of the Gaussian pyramid.
References BlurImage(), DOUBLE_BASE_IMAGE_SIZE, Image::doubleSizeImage2(), Image::height, INITSIGMA, SIGMA, and Image::width.
Referenced by getPatches(), and RecalcKeys().
void KeypointDetector::writeKeysToFile (vector< Keypoint * > & keys, char * fn) [static]
Writes keypoints to a file.
Parameters
keys Keypoints to be written.
fn File name of output.
References DOUBLE_BASE_IMAGE_SIZE, and EPCALEN.
Referenced by main().
void KeypointDetector::writePatchesToFile (vector< Keypoint * > & keys, char * fn, int patchsize) [static]
Write patches to file.
Parameters
keys Keypoints to be written.
fn File name of output.
patchsize size of square patch in pixels.
References DOUBLE_BASE_IMAGE_SIZE.
Referenced by main().
Member Data Documentation
float KeypointDetector::avgs[GPLEN] [private]
average local descriptor value. Used in PCA.
Referenced by KeypointDetector(), and MakeKeypointPCA().
float KeypointDetector::eigs[EPCALEN][GPLEN] [private]
PCA basis vectors.
Referenced by KeypointDetector(), and MakeKeypointPCA().
The documentation for this class was generated from the following files:
keypoint.h
keypoint.cc