Image Class Reference
Image class.
#include <image.h>
Public Member Functions
Image (int width, int height)
Constructs new black image.
Image (int width, int height, float *new_data)
Constructs new image with existing data.
Image (const char *filename)
Constructs new image from file (PGM only).
~Image ()
Image * clone ()
Clones a copy of the image.
Image * halfSizeImage ()
Returns a new image that's half the size of the current image.
Image * doubleSizeImage ()
Returns a new image that's double the size of the current image.
Image * doubleSizeImage2 ()
Returns a new image that's almost double the size of the current image.
void sub (Image *im2, Image *dst)
Subtracts two images.
void write (const char *filename)
Write image to a file (PGM only).
void setPixel (int x, int y, float val)
Sets pixel to a value.
float getPixel (int x, int y)
Gets the value of a pixel at a location.
float getPixelBI (float x, float y)
Gets the value of a pixel at a location with bilinear interpolation.
Public Attributes
int width
Width of image in pixels.
int height
Height of image in pixels.
float ** pix
Storage of image.
Private Member Functions
void newImage (int width, int height)
Allocates memory for new image.
Detailed Description
Image class.
Constructor & Destructor Documentation
Image::Image (int width, int height)
Constructs new black image.
Parameters
width width in pixels of new image
height height in pixels of new image
References newImage().
Referenced by BlurImage(), clone(), doubleSizeImage(), doubleSizeImage2(), and halfSizeImage().
Image::Image (int width, int height, float * new_data)
Constructs new image with existing data.
Copies new_data into own data structure.
Parameters
width width in pixels of new image
height height in pixels of new image
new_data image data to copy.
References height, pix, and width.
Image::Image (const char * filename)
Constructs new image from file (PGM only).
References height, newImage(), pix, and width.
Image::~Image ()
References pix.
Member Function Documentation
Image * Image::clone ()
Clones a copy of the image.
Returns
Cloned copy.
References height, Image(), pix, and width.
Referenced by KeypointDetector::BuildGaussianOctaves(), and KeypointDetector::BuildGaussianScales().
Image * Image::doubleSizeImage ()
Returns a new image that's double the size of the current image.
Does not antialiase in any way.
Returns
New double sized image
References getPixel(), height, Image(), setPixel(), and width.
Image * Image::doubleSizeImage2 ()
Returns a new image that's almost double the size of the current image.
Bilinear interpolate between pixels
Returns
New double sized image
References getPixel(), height, Image(), setPixel(), and width.
Referenced by KeypointDetector::ScaleInitImage().
float Image::getPixel (int x, int y)
Gets the value of a pixel at a location.
Does NOT check for bounds.
Parameters
x x pixel location
y y pixel location
Returns
pixel value
References height, pix, and width.
Referenced by ConvolveLocHeight(), ConvolveLocWidth(), doubleSizeImage(), doubleSizeImage2(), halfSizeImage(), sub(), and write().
float Image::getPixelBI (float x, float y)
Gets the value of a pixel at a location with bilinear interpolation.
If location is out of bounds, then return value of closest pixel.
Parameters
x x pixel location
y y pixel location
Returns
pixel value
References height, pix, and width.
Referenced by KeypointDetector::MakeKeypointPatch(), and KeypointDetector::MakeLocalPatch().
Image * Image::halfSizeImage ()
Returns a new image that's half the size of the current image.
Rounds image sizes down. Does not antialiase in any way.
Returns
New half sized image
References getPixel(), height, Image(), setPixel(), and width.
Referenced by KeypointDetector::BuildGaussianOctaves().
void Image::newImage (int width, int height) [private]
Allocates memory for new image.
Parameters
width width in pixels of new image
height height in pixels of new image
References height, pix, and width.
Referenced by Image().
void Image::setPixel (int x, int y, float val)
Sets pixel to a value.
Does NOT check for bounds.
Parameters
x x pixel location
y y pixel location
val Value to set.
References height, pix, and width.
Referenced by Convolve1DHeight(), Convolve1DWidth(), doubleSizeImage(), doubleSizeImage2(), halfSizeImage(), KeypointDetector::MakeKeypointPatch(), KeypointDetector::MakeLocalPatch(), KeypointDetector::readPatchesFromFile(), and sub().
void Image::sub (Image * im2, Image * dst)
Subtracts two images.
dst = this_image - im2.
Parameters
im2 Image to subtract
dst Destination image.
References getPixel(), height, setPixel(), and width.
void Image::write (const char * filename)
Write image to a file (PGM only).
Parameters
filename File name for output.
References getPixel(), height, and width.
Member Data Documentation
int Image::height
Height of image in pixels.
Referenced by BlurImage(), KeypointDetector::BuildGaussianOctaves(), KeypointDetector::BuildGaussianScales(), clone(), Convolve1DHeight(), Convolve1DWidth(), ConvolveLocHeight(), doubleSizeImage(), doubleSizeImage2(), getPixel(), getPixelBI(), halfSizeImage(), Image(), main(), newImage(), KeypointDetector::ScaleInitImage(), setPixel(), sub(), and write().
float** Image::pix
Storage of image.
Referenced by clone(), getPixel(), getPixelBI(), Image(), newImage(), setPixel(), and ~Image().
int Image::width
Width of image in pixels.
Referenced by BlurImage(), KeypointDetector::BuildGaussianOctaves(), KeypointDetector::BuildGaussianScales(), clone(), Convolve1DHeight(), Convolve1DWidth(), ConvolveLocWidth(), doubleSizeImage(), doubleSizeImage2(), getPixel(), getPixelBI(), halfSizeImage(), Image(), main(), newImage(), KeypointDetector::ScaleInitImage(), setPixel(), sub(), and write().
The documentation for this class was generated from the following files:
image.h
image.cc