gathergrads.cc File Reference
#include <stdio.h>
*
#include `config.h`
*
#include `image.h`
*
#include `keypoint.h`
*
Functions
void writeGrads (vector< Keypoint * > &keys, FILE *fp)
int main (int argc, char *argv[])
Function Documentation
int main (int argc, char * argv[])
References KeypointDetector::readPatchesFromFile(), and writeGrads().
void writeGrads (vector< Keypoint * > & keys, FILE * fp)
References Normvec().
Referenced by main().