getpatches.cc File Reference
#include <stdio.h>
*
#include `config.h`
*
#include `image.h`
*
#include `keypoint.h`
*
Functions
int main (int argc, char *argv[])
Function Documentation
int main (int argc, char * argv[])
References KeypointDetector::getPatches(), Image::height, KeypointDetector::readKeysFromFile(), Image::width, and KeypointDetector::writePatchesToFile().