image.cc File Reference
#include <stdlib.h>
*
#include <assert.h>
*
#include <stdio.h>
*
#include <string.h>
*
#include <math.h>
*
#include <pgm.h>
*
#include `config.h`
*
#include `image.h`
*
Macros
#define GAUSSKERN 4
#define PI 3.14159265358979323846
Functions
void normalizeMat (vector< vector< float > > &mat)
Normalizes a matrix to unit length.
void normalizeVec (vector< float > &vec)
Normalizes a vector to unit length.
vector< float > GaussianKernel1D (float sigma)
Creates a 1D Gaussian kernel.
float ConvolveLocWidth (vector< float > &kernel, Image *src, int x, int y)
Convolve an image along the X direction at a particular pixel location.
void Convolve1DWidth (vector< float > &kern, Image *src, Image *dst)
float ConvolveLocHeight (vector< float > &kernel, Image *src, int x, int y)
Convolve an image along the Y direction at a particular pixel location.
void Convolve1DHeight (vector< float > &kern, Image *src, Image *dst)
void BlurImage (Image *src, Image *dst, float sigma)
Does Gaussian smoothing of an image.
vector< vector< float > > GaussianKernel2D (float sigma)
Calculates a 2D Gaussian kernel.
Macro Definition Documentation
#define GAUSSKERN 4
Referenced by GaussianKernel1D(), and GaussianKernel2D().
#define PI 3.14159265358979323846
Referenced by GaussianKernel1D(), and GaussianKernel2D().
Function Documentation
void BlurImage (Image * src, Image * dst, float sigma)
Does Gaussian smoothing of an image.
Parameters
src Source image
dst Destination image
sigma Sigma of Gaussian weighting function.
References Convolve1DHeight(), Convolve1DWidth(), GaussianKernel1D(), Image::height, Image::Image(), and Image::width.
Referenced by KeypointDetector::BuildGaussianScales(), and KeypointDetector::ScaleInitImage().
void Convolve1DHeight (vector< float > & kern, Image * src, Image * dst)
References ConvolveLocHeight(), Image::height, Image::setPixel(), and Image::width.
Referenced by BlurImage().
void Convolve1DWidth (vector< float > & kern, Image * src, Image * dst)
References ConvolveLocWidth(), Image::height, Image::setPixel(), and Image::width.
Referenced by BlurImage().
float ConvolveLocHeight (vector< float > & kernel, Image * src, int x, int y)
Convolve an image along the Y direction at a particular pixel location.
Parameters
kernel Kernel to convolve with.
src Source image
x x pixel location
y y pixel location
Returns
Convolved value at location (x, y)
References Image::getPixel(), and Image::height.
Referenced by Convolve1DHeight().
float ConvolveLocWidth (vector< float > & kernel, Image * src, int x, int y)
Convolve an image along the X direction at a particular pixel location.
Parameters
kernel Kernel to convolve with.
src Source image
x x pixel location
y y pixel location
Returns
Convolved value at location (x, y)
References Image::getPixel(), and Image::width.
Referenced by Convolve1DWidth().
vector<float> GaussianKernel1D (float sigma)
Creates a 1D Gaussian kernel.
Kernel is always odd.
Parameters
sigma Sigma of Gaussian weighting function.
Returns
1D Gaussian kernel
References GAUSSKERN, normalizeVec(), and PI.
Referenced by BlurImage().
vector<vector<float> > GaussianKernel2D (float sigma)
Calculates a 2D Gaussian kernel.
Parameters
sigma Sigma of Gaussian weighting function.
Returns
2D matrix of kernel.
References GAUSSKERN, normalizeMat(), and PI.
void normalizeMat (vector< vector< float > > & mat)
Normalizes a matrix to unit length.
Parameters
mat Matrix to normalize
Referenced by GaussianKernel2D().
void normalizeVec (vector< float > & vec)
Normalizes a vector to unit length.
Parameters
vec vector to normalize
Referenced by GaussianKernel1D().