image.h File Reference
#include <vector>
*
Classes
class Image
Image class.
Functions
void BlurImage (Image *src, Image *dst, float sigma)
Does Gaussian smoothing of an image.
vector< vector< float > > GaussianKernel2D (float sigma)
Calculates a 2D Gaussian kernel.
void GaussianBlur (Image *image, float sigma)
Function Documentation
void BlurImage (Image * src, Image * dst, float sigma)
Does Gaussian smoothing of an image.
Parameters
src Source image
dst Destination image
sigma Sigma of Gaussian weighting function.
References Convolve1DHeight(), Convolve1DWidth(), GaussianKernel1D(), Image::height, Image::Image(), and Image::width.
Referenced by KeypointDetector::BuildGaussianScales(), and KeypointDetector::ScaleInitImage().
void GaussianBlur (Image * image, float sigma)
vector<vector<float> > GaussianKernel2D (float sigma)
Calculates a 2D Gaussian kernel.
Parameters
sigma Sigma of Gaussian weighting function.
Returns
2D matrix of kernel.
References GAUSSKERN, normalizeMat(), and PI.